### ISSUE TITLE
Launch crashes on 32bit OS

### ISSUE THREAD

**Issue by idontveapc** [swarajkumarsingh/browser_app#1]

**Comment by magtapptest** [comment]
Can you provide more info on this

**Comment by idontveapc** [comment]
It just crashes on startups. You tap the icon then launch display and crash. Android 11 GO (32-bit).

**Comment by swarajkumarsingh** [comment]
ok, let me check

**Comment by swarajkumarsingh** [comment]
Maybe, try on another latest Android versions.
